### ISSUE TITLE
create team for infra partner engineer

### ISSUE THREAD

**Issue by np-ktakahiro** [NP-TWN/.github#15]
## Background
kyuta: AFTEE infra partner engineer needs to maintain github repository.
current team is only for BA proper
I want to avoid to invite user one by one. I want to manage only team.

## Tasks
- [x] name new team
- [x] create new team
- [x] add kyuta to new team

## Result
- new team is created

**Comment by np-ktakahiro** [comment]
ref: 
[TWBA-operators](https://github.com/orgs/NP-TWN/teams/twba-operators)

name idea
- TWBA-infra
- TWBA-partner
- TWBA-infra-mentainer
- TWBA-infra-all and TWBA-infra-proper

**Comment by NPTW-canni** [comment]
@np-ktakahiro 
I think any of the names above is ok!
You can add here: https://github.com/orgs/NP-TWN/teams

Maybe
- TWBA-partners (parent team)
  - infra (child team)

so when you tag it is split by /, it is like @TWBA-partners/infra

**Comment by np-ktakahiro** [comment]
https://netprotections.slack.com/archives/C05MY2K4XBP/p1702446198583069

**Comment by np-ktakahiro** [comment]
![スクリーンショット 2023-12-13 14 54 39](https://github.com/NP-TWN/.github/assets/97233363/456d2dc8-5368-4f24-944e-51067910f820)
crated
